(* open! Core *)
(* open! Bonsai *)
(**)
(* module Hand_finger : sig *)
(*   (* val make *) *)
(*   (*   :  metric:Metric.t *) *)
(*   (*   -> diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> (float, float) t Bonsai.t *) *)
(**)
(*   val diff_row_bigram_data *)
(*     :  bigram_data:Bigram_data.info Key.Id.Pair.Map.t Bonsai.t *)
(*     -> Bonsai.graph *)
(*     -> Bigram_data.t Hand_finger.Map.t Bonsai.t *)
(**)
(*   (* val sfb *) *)
(*   (*   :  diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> (float, float) t Bonsai.t *) *)
(*   (**) *)
(*   (* val sfs *) *)
(*   (*   :  diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> (float, float) t Bonsai.t *) *)
(*   (**) *)
(*   (* val speed *) *)
(*   (*   :  diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> (float, float) t Bonsai.t *) *)
(*   (**) *)
(*   (* val sfb_worst *) *)
(*   (*   :  diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> worst_counter:int Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> ((string * float) list, float) t Bonsai.t *) *)
(*   (**) *)
(*   (* val sfs_worst *) *)
(*   (*   :  diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> worst_counter:int Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> ((string * float) list, float) t Bonsai.t *) *)
(*   (**) *)
(*   (* val speed_worst *) *)
(*   (*   :  diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *) *)
(*   (*   -> worst_counter:int Bonsai.t *) *)
(*   (*   -> Bonsai.graph *) *)
(*   (*   -> ((string * float) list, float) t Bonsai.t *) *)
(* end *)
