(* open! Core *)
(* open! Bonsai *)
(* open! Bonsai.Let_syntax *)
(**)
(* module Derp = struct *)
(*   module Metric = struct end *)
(* end *)
(**)
(* module Stats = struct *)
(**)
(*   let worst *)
(*         ~(kind : Metric.Kind.t) *)
(*         ~(diff_row_bigram_data : Bigram_data.t Hand_finger.Map.t Bonsai.t) *)
(*         ~(worst_counter : int Bonsai.t) *)
(*         graph *)
(*     = *)
(*   ;; *)
(**)
(*   (* let sfb = make ~metric:Sfb *) *)
(*   (* let sfs = make ~metric:Sfs *) *)
(*   (* let speed = make ~metric:Speed *) *)
(*   (* let sfb_worst = worst ~metric:Sfb *) *)
(*   (* let sfs_worst = worst ~metric:Sfs *) *)
(*   (* let speed_worst = worst ~metric:Speed *) *)
(* end *)
(* module C : sig *)
(*   val component *)
(*     :  metric_kinds:Metric.Kind.Set.t Bonsai.t *)
(*     -> worst_counter:int Bonsai.t *)
(*     -> diff_row_bigram_data:Bigram_data.t Hand_finger.Map.t Bonsai.t *)
(*     -> Bonsai.graph *)
(*     -> Metric.t Metric.Kind.Map.t Bonsai.t *)
(* end = struct end *)
(**)
(* include C *)
